# General

- For example, probabilistic models of cognition suggest that a broad range of different assumptions about how people may structurally represent input information are required to capture their inferences about the extensions of novel properties in different inductive contexts [@griffithsProbabilisticModelsCognition2010; @kempStructuredStatisticalModels2009].

# Sections

## Introduction 

- Of course, the whole argument rests on the assumption that the mind is indeed sensitive to whatever relations the alternatives have with each other, however, it is hard to think of a situation
- In other words, by the end of the decision making process as illustrated in Figure 1, the selected choice alternatives form the exact same subset as the one which is indicated by a given selection criterion. 

- Footnote 2: The literature on behavioral decision research usually forgoes the admittedly technical definition of probability spaces and defines prospects as probability mass functions. Nonetheless, even though probability spaces are idealized models, they provide a useful mathematical foundation for the case where the simultaneous occurrence of more than one elementary outcome is of interest.

## Section 1: Properties / Selection Criteria / Sampling 

## Section 2: Underweighting / Hills and Hertwig / etc.

Hills and Hertwig [-@hillsInformationSearchDecisions2010] discussed a potential link between sampling and decision strategies in DfE. 
Specifically, the authors suppose that if single samples originating from different prospects are generated in direct succession (piecewise sampling), the evaluation of prospects is based on multiple ordinal comparisons of single samples (round-wise decisions).
In contrast, if single samples originating from the same prospect are generated in direct succession (comprehensive sampling), it is supposed that the evaluation of prospects is based on a single ordinal comparison of long sequences of single samples (summary decisions) [@hillsInformationSearchDecisions2010, Figure 1 for a graphical summary]. 

We now consider choices between two prospects and the assumptions of Hills and Hertwig [-@hillsInformationSearchDecisions2010] in more detail to build the respective stochastic sampling model for DfE.

Let $X$ and $Y$ be random variables defined on the prospects $(\Omega_X, \mathcal{F}_X, P_X)$ and $(\Omega_Y, \mathcal{F}_Y, P_Y)$. 

Hills and Hertwig [-@hillsInformationSearchDecisions2010] suggest that any two sample sequences $X_i$ and $Y_i$ are compared by their means. 
Let thus $C = \mathbb{R}$ be the set of all possible outcomes of the comparison of the means over two unordered sequences $X_i$ and $Y_i$ of given lengths $N_X$ and $N_Y$.
That is, each element $c \in C$ represents a pair $X_i \cap Y_i$ with a unique combination of the number of times any possible realization of $X$ and $Y$ occurs. 
Let then

$$
\mathcal{G} = \left\{B_1 = \{c \in C: \overline{X}_{N_X} - \overline{Y}_{N_Y} > 0\}, B_2 = \{ c \in C: \overline{X}_{N_X} - \overline{Y}_{N_Y} \leq 0\}
\right\}
$$

be a set of subsets of $C$, indicating that comparisons of prospects on the ordinal (rather than on the metric) scale are of primary interest. 
We denote a single ordinal comparison by the event space $(C, \mathcal{G})$.
The observed outcome of such an ordinal comparison can be regarded as evidence for or against a prospect and the number of wins over a series of independent ordinal comparisons as accumulated evidence. 
To integrate the concept of evidence accumulation into the current model, we let the decision variable $D$ be a measurable function 

$$
D: C \mapsto C'
$$

that maps the possible outcomes of a mean comparison in $C$ onto a measure space $C' = \{0,1\}$, with $0$ $(1)$ indicating a lost (won) comparison:

$$
D(c \in C) \in C' = 
  \begin{cases}
    1 \quad \text{for} \quad \{c \in C: (\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0)\}  \in \mathcal{G} \\
    0 \quad \text{else}. 
  \end{cases} 
$$

It can be shown that for fixed sequence lengths $N_X$ and $N_Y$, a sequence $D_i = D_1, ..., D_n$ representing multiple independent comparisons is a Bernoulli process where the number of won comparisons follows the binomial distribution

$$
D \sim \mathcal{B}\left( p \left(\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0\right), n\right) \; ,
$$

with $p$ denoting probability of $X_i$ winning a single comparison, i.e., the probability of success, and $n$ denoting the number of comparisons.

It becomes evident that the two combinations of sampling and decision strategies proposed by Hills and Hertwig [-@hillsInformationSearchDecisions2010] are reflected in certain restrictions on the free parameters $N_X, N_Y$ and $n$ of the sampling model and that these restrictions translate to the shape of the binomial distribution associated to the decision variables, straightforwardly via the parameter $n$, more interestingly, however, via its parameter $p$. 

I.e., first, whether a single (summary decision) or multiple ordinal comparisons (round-wise decision) are conducted, is reflected by the length of the sequence $D_i = D_1, ..., D_n$, with $n = 1$ for summary decisions and $n \geq 1$ for round-wise decisions. 
The idea that multiple comparisons may be conducted can be formalized by extending the event space $(C, \mathcal{G})$ of a single comparison to its $n$-fold product 

$$
\left(\prod_{i = 1}^{n} C_i, \bigotimes_{i = 1}^{n} \mathcal{G}_i \right)
\; ,
$$

where $i \in \{1, ..., n\}$ denotes the number of comparisons. 

Second, whether comparisons are conducted on the basis of longer sample sequences or single samples is reflected by the lengths of sample sequences from the same prospect with $N_X, N_Y \geq 1$ for comprehensive sampling and $N_X = N_Y = 1$ for piecewise sampling. 

Note now that, in order to derive predictions of the choice behavior from the current stochastic model, the full product model

$$
\left(\prod_{i = 1}^{n} C_i, \bigotimes_{i = 1}^{n} \mathcal{G}_i, \bigotimes_{i = 1}^{n} P_i \right)
\; ,
$$

including the probability measure $P$, which assigns each $c \in C$, and each $B \in \mathcal{G}$ respectively, a probability, must be identified. 
Although this can be demonstrated for the random variables considered so far, it becomes rather quickly intractable with increasing elements in $\Omega$ and growing sequence lengths. 
However, by explicating the above probability measure ([Appendix 1][Appendix 1: Probability Measure Over Sample Mean Comparisons]), it becomes evident that it is largely influenced by the underlying sequence lengths $N_X$ and $N_Y$.
In the following section and a subsequent simulation analysis, we demonstrate that this influence is of such a form that it produces some principle and predictable trends in the choice behavior that can be modeled in the cumulative prospect theory.

Note first that the current stochastic sampling model allows to treat sampling and decision strategies independently by parameterization of both lengths of sample sequences and the number of comparisons.    

## Section 3: Representation  

In quite many cases, however, a number of different representations can be used to describe the properties of choice alternatives in a given set.
Yet, not every representation permits an accurate description of a given property at reasonable expenses or allows to describe a property at all [cf. @marrRepresentationRecognitionSpatial1978].
E.g., a consequential difference that has emerged in behavioral research on risky choice is whether the probability of a risky outcome is described using a decimal number (.2), ratio (2/10), or percentage (20%), or whether it must be inferred from the relative frequency of occurrence of the particular outcome in a collection of independent and identically distributed (i.i.d.) random variables, i.e., a *random sample*.
Noteworthy, for the latter case, which is usually referred to as decisions from experience, empirical protocols indicate that people decide as if they were underweighting small probability events [@barronSmallFeedbackbasedDecisions2003; @hertwigDecisionsExperienceEffect2004; @weberPredictingRiskSensitivity2004].
One undisputed factor that contributes to this underweighting pattern is the sampling error associated with people's reliance on small samples [e.g., @foxDecisionsExperienceSampling2006; @hertwigDecisionsExperienceEffect2004; @hauDescriptionexperienceGapRisky2008; @ungemachAreProbabilitiesOverweighted2009; see also @wulffMetaanalyticReviewTwo2018 for a meta-analytic review], indicating that, although the probabilities of outcomes can in principle be accurately described in decisions from experience, the actual description is rather inaccurate because it cannot be done at reasonable expenses.  

Another property of choice alternatives that is likely to play a role in risky choice but can only be made explicit using a sample representation as in decisions from experience is the sequence in which outcomes occur.
Although a discrete-time collection of i.i.d. random variables cannot, by definition, exhibit temporal regularity, i.e., it cannot produce a stable sequence of sampled outcomes, spurious temporal patterns might nevertheless be regarded as a property of choice alternatives and affect the consequential choice behavior. 
Indeed, the underweighting pattern and other behavioral phenomena like the wavy recency effect and probability matching, are reasonably well captured by models which incorporate the assumption that people rely on (spurious) outcome sequences [@cohenEffectPerceivedPatterns2021; @gaissmaierSmartPotentialProbability2008; @plonskyRelianceSmallSamples2015; @plonskyLearningSettingsPartial2017;  @yuSequentialEffectsSupersition2009]. 
 
The preceding two examples illustrate how some properties of choice alternatives can be described in one representation but not in another and how representations can differ with regards to the processing effort required to describe the same property.
Thus, there is generally a trade-off between different representations, where in a given representation certain properties become explicit while others are pushed into the background [@marrVisionComputationalInvestigation1982, p. 21].


## Section 4: Simulation Study

# Appendix

## A1: Probability Measure Over Sample Mean Comparisons

To proof is that the sequence $D_i = D_1, ..., D_n$ describes a Bernoulli process with the number of won comparisons following the binomial distribution $\mathcal{B}\left(p(\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0), n \right)$ for fixed sequence lengths $N_X$ and $N_Y$.

Therefore we must demonstrate that the probability of success, i.e., $p \left(\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0\right)$, is identified.
The derivation chain is first roughly paraphrased and then formalized as a mathematical equation. 

We start by noting that the probability of success equals the probability of the subset $B_1 \in \mathcal{G}$ which contains all comparisons $c \in C$ that satisfy the inequation $\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0$.
Since the probability of the subset $B_1$ equals the probability that any of its elements occurs, the probabilities of all $c \in B_1$ are summed up. 
We therefore use the sum operator with the limits $j \in \{1, ..., |B_1|\}$, with $|B_1|$ denoting the cardinality of the set $B_1$, i.e., the number of elements within the set. 
As a major assumption is that the random variables within a sample sequence are iid and independent across sequences, the joint probability of a pair $\overline{X}_{N_X} \cap \overline{Y}_{N_Y}$, i.e., a pair $X_i \cap Y_i$ with a unique combination of the number of times any possible realization of $X$ and $Y$ occurs, is described by the product of their individual probabilities $p(\overline{X}_{N_X})$ and $p(\overline{Y}_{N_Y})$.
Finally, to get these individual probabilities, we must determine the probability that each possible realization indeed occurs the respective number of times in the underlying sample sequence.
This probability is given by the multinomial distribution which reduces to a binomial distribution in the case of only two possible realizations. 
We denote the number of times a realization occurs in a sample sequence with $k_{\omega}$, where $\omega$ signals that the realizations of the random variables are numerical equivalent to the outcomes in the sample space of the prospects.  

$$
  \begin{split}
    p(D = 1) 
      & = p \left( \; B_1 = \{c \in C: (\overline{X}_{N_X} - \overline{Y}_{N_Y} > 0)\} \in \mathcal{G} \; \right) \\\\\\ 
      & = \sum_{j=1}^{|B_1|} \left( \;
          p(\overline{X}_{N_Xj})  
          \times 
          p(\overline{Y}_{N_Yj}) \; 
        \right)_{j \, \in \, \{1, ..., |B_1|\}} \\\\\\
      & = \sum_{j=1}^{|B_1|} \left( \; 
        p \left( 
          \frac{1}{N_X} \sum\limits_{i = 1}^{N_X} X(\omega \in \Omega_X)_{ij}
        \right) 
        \times
        p \left( 
          \frac{1}{N_Y} \sum\limits_{i = 1}^{N_Y} Y(\omega \in \Omega_Y)_{ij}
        \right) \; 
        \right)_{j \, \in \, \{1, ..., |B_1|\}} \\\\\\
      & = \sum_{j=1}^{|B_1|} \left( \;
        \left(
          {N_X\choose k_{\omega_{1X}j}, ..., k_{\omega_{nX}j}} \prod_{\omega_{iX} \in \Omega_X} p(\omega_{iX})^{k_{\omega_{iX}j}}
        \right)
        \times
        \left(
        {N_Y\choose k_{\omega_{1Y}j}, ..., k_{\omega_{nY}j} } \prod_{\omega_{iY} \in \Omega_Y} p(\omega_{iY})^{k_{\omega_{iY}j}}
        \right)
        \right)_{j \, \in \, \{1, ..., |B_1|\}} \\\\\\
      & = \sum_{j=1}^{|B_1|} \left( \;
        \left(
          \frac{N_X!}{k_{\omega_{1X}j}! \times ... \times k_{\omega_{nX}j}!} 
          \times 
          p(\omega_{1X})^{k_{\omega_{1X}j}} 
          \times 
          ... 
          \times p(\omega_{nX})^{k_{\omega_{nX}j}}
        \right)
        \times
        \left(
          \frac{N_Y!}{k_{\omega_{1Y}j}! \times ... \times k_{\omega_{nY}j}!} 
          \times 
          p(\omega_{1Y})^{k_{\omega_{1Y}j}} 
          \times 
          ... 
          \times p(\omega_{nY})^{k_{\omega_{nY}j}}
        \right)
      \right)_{j \, \in \, \{1, ..., |B_1|\}}
  \end{split}
$$

## A2: Choice Problems 

```{r message=FALSE}
gambles <- read_csv("data/gambles/sr_subset.csv")
gambles %>% apa_table()
```


